// <auto-generated />
namespace Clony_Exemplo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CriarTabelas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriarTabelas));
        
        string IMigrationMetadata.Id
        {
            get { return "201406291926077_CriarTabelas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
